### PR TITLE
ControlPanel: Move syntax of GetNetwork and SetNetwork

### PR DESCRIPTION
**Pull request by ChasedSpade**
Fix command syntax of GetNetwork and SetNetwork.

### CODE REVIEW

**Comment by DarthGandalf** [comment]
Uh, I should test stuff better before merging :(
This crashes when doing `/msg *controlpanel getnetwork nick $me` because `pNetwork == nullptr` (thx @KindOne- and Uptime)

**Comment by ChasedSpade** [comment]
Here's the patch for controlpanel. Sorry about that. https://gist.github.com/ChasedSpade/456a82c28fa2dbc7ad82

**Comment by DarthGandalf** [comment]
@ChasedSpade this would fail when you're editing some other user, but *you* are connected to a network

**Comment by ChasedSpade** [comment]
Updated the Gist with a better patch (hopefully)

**Pull request merged**
