### PR TITLE
nickserv: use NICKSERV instead of PRIVMSG

### PR DESCRIPTION
**Pull request by Mikaela**
This is same as #833, but to correct  branch.
Closes #833

### CODE REVIEW

**Comment by jpnurmi** [comment]
Personally I'd prefer master. This is a behavioral change that _may_ break things for some.

**Comment by Mikaela** [comment]
Closing because of previous commit.

**Comment by DarthGandalf** [comment]
J-P, may you write some guide explaining which changes should go to which
branch? So far you were saying about changes to znc.conf and .h

2015-02-18 23:28 GMT-08:00 Mikaela Suomalainen <notifications@github.com>:

**Comment by jpnurmi** [comment]
I started http://wiki.znc.in/Branches wiki page. I'll collect more examples on the list when something comes up. This particular change is IMHO in the "behavioral change" category.

**Pull request closed without merging**
