### PR TITLE
Update modtcl.cpp add tcl function GetNetworkName

### PR DESCRIPTION
**Pull request by artispretis**
Add tcl function [GetNetworkName] return name of current network

### CODE REVIEW

**Comment by DarthGandalf** [comment]
Did you test this at all?

**Comment by artispretis** [comment]
> Did you test this at all?

Yes. I use it in production. No problem to report.

`<MalaGaM> return $network
<*modtcl> artis
<MalaGaM> return $::network
<*modtcl> artis
<MalaGaM> return [GetServerName]
<*modtcl> artis`

**Comment by DarthGandalf** [comment]
The reason I'm asking is you're using `GetNetworkName` in one place, but `GetServerName` in another. How can `Tcl_CreateCommand(interp, "GetNetworkName", ...)` make `GetServerName` available?

**Comment by artispretis** [comment]
> The reason I'm asking is you're using GetNetworkName in one place, but GetServerName in another. How can Tcl_CreateCommand(interp, "GetNetworkName", ...) make GetServerName available?

fixed to https://github.com/znc/znc/pull/1658 sorry

**Pull request closed without merging**
