### PR TITLE
perform: add descriptions for commands

### LINKED ISSUE #1100: /znc *perform help is missing descriptions
```
<*perform> ------
<*perform> Command: Add <command>
<*perform> ------
<*perform> Command: Del <nr>
<*perform> ------
<*perform> Command: Execute 
<*perform> ------
<*perform> Command: Help search
<*perform> Description: Generate this output
<*perform> ------
<*perform> Command: List 
<*perform> ------
<*perform> Command: Swap <nr> <nr>
<*perform> ------
```

Only the help has Description on what it does, while the messages might seem obvious, having small descriptions on what they do would be nice.

* Adds perform command to be sent to the server on connect
* Delete a perform command
* Send the perform commands to the server now
* *already descripted*
* List the perform rules
* Swap two perform commands

I don't know how to add descriptions for commands and #1090 prevents me from even trying to add new lines.

* * * * *

* Debian GNU/Linux 7.9 (wheezy)
    * ZNC 1.7.x-git-397-2c0dfbb - http://znc.in
    * IPv6: yes, SSL: yes, DNS: threads, charset: yes

<bountysource-plugin>
---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/26797869-znc-perform-help-is-missing-descriptions?utm_campaign=plugin&utm_content=tracker%2F1759&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F1759&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by Mikaela**
Thanks @ChasedSpade

Closes #1100
Closes #1102

### CODE REVIEW

**Comment by dgw** [comment]
I don't believe the Travis build will complete successfully, as AddCommand() needs a string of command arguments (even if empty) based on what I see in other modules. Created #1102 preemptively for this reason.

**Comment by Mikaela** [comment]
It appears that the build did pass, but I don't know if it would have failed while loading.

**Comment by DarthGandalf** [comment]
`AddCommand()` has certain default arguments... http://docs.znc.in/classCModule.html#a7b25f6d0ed7e92dcc18d3b11a2c48398

**Comment by Mikaela** [comment]
Help wanted!

**Comment by Mikaela** [comment]
It seems that I got the build fixed, but any comments (and how to fix) would be appreciated if there is something wrong.

**Pull request merged**
