### PR TITLE
1.8.x /translations/pl_PL

### PR DESCRIPTION
**Pull request by tojestzart**
[pl_PL.tar.gz](https://github.com/znc/znc/files/4781463/pl_PL.tar.gz)
EOF at line 2

### CODE REVIEW

**Comment by DarthGandalf** [comment]
What is this?

**Comment by tojestzart** [comment]
i dont have idea, dont know how to create properly pull request, just have a look on that tar file

**Comment by DarthGandalf** [comment]
If you wanted to add your new translations to the source, it's done automatically by jenkins every night. In fact, the commits which you tried to merge in this PR are examples of that.

https://jenkins.znc.in

**Comment by psychon** [comment]
Does jenkins also add new translations automatically? Does PL need a new file in https://github.com/znc/znc/tree/master/translations?

**Comment by DarthGandalf** [comment]
> Does jenkins also add new translations automatically?

.po files, yes

> Does PL need a new file in https://github.com/znc/znc/tree/master/translations?

That file needs to be added.

**Pull request closed without merging**
