### PR TITLE
Show client identification in notify_connect module

### PR DESCRIPTION
**Pull request by BlaXpirit**
If someone connects to ZNC as `username@identifier/network`, the module will now show that *identifier*. When the identifier is not provided, the behavior is unchanged.

> [Notice] -\*status- \*\*\* username@identifier detached (from 127.0.0.1)

### CODE REVIEW

**Comment by DarthGandalf** [comment]
May you add a test for it?
At this point we have enough infrastructure to make this easy (`make test2` and `test/Integration.cpp`)

**Comment by BlaXpirit** [comment]
If this module had tests, I would gladly extend them. But I have no idea how to add new ones.

**Comment by Mikaela** [comment]
[Clientnotify](http://wiki.znc.in/Clientnotify) could probably also use this change as I don't think it has identifier either.

**Comment by BlaXpirit** [comment]
@Mikaela Interesting. This change is even more relevant to *clientnotify*, and the module is more relevant to me, but I wasn't aware of it!

**Comment by Mikaela** [comment]
I believe that the two modules  should be merged and same with automode/autoop. They do so similar thing and better than two separate modules would be just having options "notify me (admin) when someone else connects" or "notify me when other clients login as me". But that is a separate issue.

**Comment by BlaXpirit** [comment]
I investigated the testing facilities.
So `make test2` requires `sudo make install`? No, thanks :neutral_face:

**Comment by DarthGandalf** [comment]
why sudo?
./configure --prefix=/tmp/znc

2015-11-27 9:44 GMT+00:00 Oleh Prypin <notifications@github.com>:

**Comment by DarthGandalf** [comment]
Oh, I've noticed you added the test...
Please comment in such cases; github doesn't notify about new commits in PR, but does about new comments.

**Comment by DarthGandalf** [comment]
Merged with this change: d7363971946c17e17aaac2fdd5a50020ded87270

**Pull request merged**
