### PR TITLE
Maybe fix build on macos

### PR DESCRIPTION
**Pull request by DarthGandalf**
@glguy please try this

### CODE REVIEW

**Comment by glguy** [comment]
> @glguy please try this

I'll give this a shot tonight and report back what I learn. Thanks!

**Comment by glguy** [comment]
I haven't narrowed it down yet, but somehow the defines in `zncconfig.h` aren't showing up in source files that seem to include them

```
[  1%] Building CXX object src/CMakeFiles/znclib.dir/znc.cpp.o
/Users/emertens/Source/znc/src/znc.cpp:117:20: error: use of undeclared identifier 'VERSION_STR'
    return CString(VERSION_STR) + CString(ZNC_VERSION_EXTRA);
                   ^
/Users/emertens/Source/znc/src/znc.cpp:484:47: error: use of undeclared identifier 'VERSION_STR'
    config.AddKeyValuePair("Version", CString(VERSION_STR));
                                              ^
/Users/emertens/Source/znc/src/znc.cpp:624:46: error: use of undeclared identifier 'VERSION_STR'
    vsLines.push_back("Version = " + CString(VERSION_STR));
                                             ^
/Users/emertens/Source/znc/src/znc.cpp:1064:20: error: use of undeclared identifier 'VERSION_MAJOR'
        make_tuple(VERSION_MAJOR, VERSION_MINOR);
                   ^
/Users/emertens/Source/znc/src/znc.cpp:1064:35: error: use of undeclared identifier 'VERSION_MINOR'
        make_tuple(VERSION_MAJOR, VERSION_MINOR);
                                  ^
/Users/emertens/Source/znc/src/znc.cpp:1068:43: error: use of undeclared identifier 'VERSION_STR'
        BackupConfigOnce("pre-" + CString(VERSION_STR));
                                          ^
6 errors generated.
```

**Comment by glguy** [comment]
OK, I deleted the znc directory and started fresh. There was cruft from an old autoconf build there that was invisible to git with the default settings.

With that done a new linker error emerges

```
[6/32] Linking CXX shared module modules/crypt.so
FAILED: modules/crypt.so
: && /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++  -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX14.0.sdk -mmacosx-version-min=13.6 -bundle -Wl,-headerpad_max_install_names  -o modules/crypt.so modules/CMakeFiles/module_crypt.dir/crypt.cpp.o  -Wl,-bundle_loader,src/znc && :
ld: Undefined symbols:
  _BN_bin2bn, referenced from:
      CCryptMod::DH1080_comp(CString&, CString&) in crypt.cpp.o
  _BN_bn2bin, referenced from:
      CCryptMod::DH1080_gen() in crypt.cpp.o
      CCryptMod::DH1080_gen() in crypt.cpp.o
...
```

**Comment by DarthGandalf** [comment]
Fix to this new error seems related to #1882 so I'll try to fix/merge that first, then will get back to macos

**Comment by DarthGandalf** [comment]
@glguy now this PR should work, can you retest?

**Comment by glguy** [comment]
> @glguy now this PR should work, can you retest?

```
 ZNC was successfully compiled.
```

**Pull request merged**
