### PR TITLE
Write config file when channel is removed (#932)

### LINKED ISSUE #932: Channels no longer removed from config despite chansaver being loaded
The chansaver module is loaded, this causes the channels I join to be added in znc.conf, however, when I part these channels again, these channels are no longer removed from the config. A workaround I discovered is to do `/znc saveconfig` every time I part a channel to make sure it gets removed from the config, because when you kill the znc process and restart znc, you will be joined to the parted channels again if you didn't do the aforementioned workaround.

<bountysource-plugin>
---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/10196381-channels-no-longer-removed-from-config-despite-chansaver-being-loaded?utm_campaign=plugin&utm_content=tracker%2F1759&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F1759&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by elyscape**
Fixes #932.

### CODE REVIEW

**Comment by DarthGandalf** [comment]
@jpnurmi this goes to 1.6.x?

**Comment by dgw** [comment]
As it's a bugfix for a regression introduced in 1.6, probably. @DarthGandalf

**Comment by elyscape** [comment]
Oh, good point.  Will retarget towards the 1.6.x branch.  Should I close this PR or leave it open?

**Comment by elyscape** [comment]
Retargeted to 1.6.x branch in #937.

**Comment by jpnurmi** [comment]
#937 was merged.

**Pull request closed without merging**
