### PR TITLE
Fix reserved identifier violation in header guards (#433)

### PR DESCRIPTION
**Pull request by jpnurmi**

### CODE REVIEW

**Comment by jpnurmi** [comment]
It could be also more exlusive ```ZNCFOO_H```, but then config.h vs. zncconfig.h would conflict.

**Comment by kylef** [comment]
Perhaps it would make more sense to move to `pragma once`. Since it's supported on all compilers that support C++11 from what I understand

**Comment by DarthGandalf** [comment]
`ZNC_FOO_H_` works

**Comment by jpnurmi** [comment]
Updated

**Comment by Kriechi** [comment]
Actually some files already use `#pragma once` - would be great to stick to one syntax.
https://github.com/znc/znc/blob/9814f2a258356356f8d3d9a527ee28c370be7085/modules/modpython/ret.h#L17
https://github.com/znc/znc/blob/9814f2a258356356f8d3d9a527ee28c370be7085/modules/modperl/pstring.h#L17
https://github.com/znc/znc/blob/9814f2a258356356f8d3d9a527ee28c370be7085/modules/modperl/module.h#L17
https://github.com/znc/znc/blob/9814f2a258356356f8d3d9a527ee28c370be7085/modules/modpython/module.h#L17

I probably prefer the pragma - because it does not require a "terminating" line at the end.

**Pull request merged**
