### PR TITLE
Display development version as "1.6.x" - ref #748

### PR DESCRIPTION
**Pull request by jpnurmi**

### CODE REVIEW

**Comment by jpnurmi** [comment]
Poll: would you prefer ```1.6.x-git-19-bd044cf``` or ```1.6-git-19-bd044cf```?

**Comment by Mikaela** [comment]
I think the first one as the .x would also be important information.

**Comment by DarthGandalf** [comment]
`x` is fine. But won't `-1` in `VERSION_PATCH` break anything?

**Comment by jpnurmi** [comment]
ZNC itself doesn't use ```VERSION_PATCH``` for anything, at least yet. :) I was considering making it a large number instead. I'm feeling a bit unsure, what would you prefer? Would it be a lie to claim that the current 1.6.x development version is greater than the upcoming 1.6.1? On the other hand, unsigned comparison for -1 would also give "wrong" result.

**Comment by DarthGandalf** [comment]
And this is reason why (earlier?) we use(d?) odd/even versions :)

2015-02-28 8:14 GMT-08:00 J-P Nurmi <notifications@github.com>:

**Comment by jpnurmi** [comment]
ZNC is also the first project I've ever seen use .x :P Others just bump the version up by one as soon as the previous release has been tagged.

**Comment by DarthGandalf** [comment]
It is you how changed output of `--version` to show `.x` :P
I did that only for branch name, which is not shown anywhere except git

**Pull request merged**
