### PR TITLE
CONTRIBUTING.md: ask -D with issues in connection

### PR DESCRIPTION
**Pull request by Mikaela**
Issue #1081 made me notice this was missing.

[CI SKIP]

### CODE REVIEW

**Comment by Mikaela** [comment]
I am unhappy with how I worded this, could someone with better English give me better wording?

**Comment by Zarthus** [comment]
What about:

```
 * If you are reporting an issue with the connectivity, please run ZNC in debug mode and include the relevant part of the output. 
    To enable debug mode, run znc with `-D`.
```

----

 * If you are reporting an issue with the connectivity, please run ZNC in debug mode and include the relevant part of the output. 
    To enable debug mode, run znc with `-D`.


It seems to me like all possible cases of `connectivity between your client and ZNC or ZNC and the IRC server` just don't need mentioning. If there is a connectivity issue, it will always be one of those options, PEBKAC aside.

**Comment by Mikaela** [comment]
Thanks

**Comment by jpnurmi** [comment]
https://github.com/znc/znc/commit/2c0dfbbe18bbed88e23256ac2b1148f12f7302f8

**Pull request closed without merging**
