### PR TITLE
Fix #872: webadmin checkboxes

### LINKED ISSUE #872: 1.6.0: when no networks are defined webadmin says that all network modules are loaded by network
run `znc --makeconf` and say "no" to creating network. Now go to webadmin and all checkboxes that say what levels the module is loaded on say that all modules that can be loaded on network level are loaded (while there are no networks).

<bountysource-plugin>
---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/8673921-1-6-0-when-no-networks-are-defined-webadmin-says-that-all-network-modules-are-loaded-by-network?utm_campaign=plugin&utm_content=tracker%2F1759&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F1759&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by jpnurmi**
Don't claim all networks/users have loaded a module when there are none

### CODE REVIEW

**Comment by jpnurmi** [comment]
Wrong branch *facepalm*

**Comment by Mikaela** [comment]
How is master wrong branch?

**Comment by jpnurmi** [comment]
This is a good example of a simple bug that can be fixed in 1.6.1. The fix will eventually get merged to master.

**Comment by Mikaela** [comment]
I thought that everything goes to master and will then be cherry-picked or merged to X.Y.Z?

**Comment by jpnurmi** [comment]
Pushing fixes to the lowest applicable/maintained stable branch, and merging them to master ensures that git history works as intended. Cherry-picking fixes between branches would mean that the same fix would end up to having different sha1 in different branches. For example, the following wouldn't then work:

    $ git branch --contains c5ab7337
      1.6
      master

**Comment by Mikaela** [comment]
I see

**Pull request closed without merging**
