### PR TITLE
WIP: refactor sockets

### PR DESCRIPTION
**Pull request by DarthGandalf**
Some things don't work yet, but this is more or less ready to review.

@psychon

### CODE REVIEW

**Comment by psychon** [comment]
I don't have much time to look at this in depth, but do I understand correctly that you took Csocket, ripped out some of the internals and replaced them with calls to https://github.com/chriskohlhoff/asio?
What's the goal here? Is this supposed to be faster, more secure, ...?

**Comment by DarthGandalf** [comment]
> do I understand correctly that you took Csocket, ripped out some of the internals

That's correct. I copied some functions over as is, but replaced most of it with asio. I chose asio because it's supposed to be included in C++20, at which point we can hopefully drop that library from dependencies and simply bump the compiler requirements.

> What's the goal here? Is this supposed to be faster, more secure, ...?

It's less monolithic, so easier to modify. The main feature here are classes `base_layer` and `optional_layer`, which are combined in `Pipeline`. Currently there are only 2 layers (TCP and SSL), but more layers I can foresee:
* encoding (for now I copied it from Csocket verbatim, but it would be cleaner as a separate layer)
* socks proxy

I got an idea to do this long time ago, when was implementing encoding support in Csocket, but now the primary motivator to finally do it was Happy Eyeballs (#241), because #1571 has certain problems (races) which are not solvable outside of Csocket.

**Comment by DarthGandalf** [comment]
@jimloco could you also take a look? Note that I didn't implement full Csocket API, but parts which map to asio relatively easy and which are used in ZNC.

**Comment by DarthGandalf** [comment]
Status update: I don't like this callback hell, so trying to rewrite this using C++20 coroutines.

**Comment by girst** [comment]
> C++20 coroutines.

as a user, I'd rather not have a dependency on such a new language standard. for example, centos7 ships with gcc 4.8--i wouldn't be able to compile znc any longer. other distributions aren't much more up to date either: ubuntu 18.04 ships 7.4 and even rhel8 and debian buster "only" ship g++ 8.3. ubuntu 20.04 will likely ship with gcc 9.2. 

according to [cppreference](https://en.cppreference.com/w/cpp/compiler_support), coroutines are supported only partially even by gcc 10; [gcc itelf](https://gcc.gnu.org/projects/cxx-status.html#cxx2a) currently says 'no support'.

**Comment by DarthGandalf** [comment]
@girst of course.

I'm not making this a hard dependency yet. The socket implementation would be selectable via cmake, and if C++20 is not available, then you'd just get the old implementation, which means that bugs which this refactor is supposed to fix won't be fixed for your setup either. I think that's a fine compromise.

**Comment by girst** [comment]
ah, good to know. that is a perfectly fine compromise!

**Comment by DarthGandalf** [comment]
Update: this code I've written is terrible, and maintainable even less than existing Csocket.

Let's wait until a networking lands in C++ standard, be it asio or something else, then will look how to do such refactor in a better way.

**Pull request closed without merging**
