### PR TITLE
src/znc.cpp: change realname to User of ZNC

### LINKED ISSUE #818: "Got ZNC?" is a little weird real name
At one IRC channel we were discussing the real name and "Got ZNC?" is a little weird. I think that something like "ZNC %VERSION%" (Supybot does this too) would be good default (if expandstrings are allowed there). There was opposition as this would make znc more exposed for targeted vulnerabilities, but it might also make users upgrade faster if that happened.

There was also another advatance of changing the default real name to anything of tracking old ZNC versions.

And of course, users can still set it as whatever they wish.

<bountysource-plugin>
---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/7838953-got-znc-is-a-little-weird-real-name?utm_campaign=plugin&utm_content=tracker%2F1759&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F1759&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by Mikaela**
Closes #818

### CODE REVIEW

**Comment by jpnurmi** [comment]
+1

**Comment by Mikaela** [comment]
Updated based on https://github.com/znc/znc/issues/818#issuecomment-141694766 except I changed the u to U as it seems more proper in realname (how while ZNC is capitalized?).

**Comment by jpnurmi** [comment]
How about just an empty default and make ```CUser::GetRealName()``` do the same thing than ```CUser::GetQuitMsg()``` does?

**Comment by Mikaela** [comment]
I don't understand that, but if you propose to make real name empty, that won't work. https://github.com/znc/znc/issues/818#issuecomment-138973335

**Comment by Mikaela** [comment]
Another update, now it's *User of ZNC*.

**Comment by Mikaela** [comment]
Closed in favour of https://github.com/znc/znc/pull/1109

**Pull request closed without merging**
