### PR TITLE
modules: Remove Q

### PR DESCRIPTION
**Pull request by Zarthus**
Probably merge-conflicts with #1651

### CODE REVIEW

**Comment by DarthGandalf** [comment]
Add the reason for the removal to the commit message

**Comment by dchmelik** [comment]
but I use Q

**Comment by DarthGandalf** [comment]
@dchmelik ok, are you going to maintain the module?

**Comment by Zarthus** [comment]
@dchmelik And you may continue to use it, you will just need to jump through one additional hoop with the pending changes.

This PR just marks the notion that ZNC will stop supporting it on an official level, because it already provides alternatives and QuakeNet are unwilling to provide generalized authentication methods like SASL.

**Pull request merged**
