### PR TITLE
Required optionals do not exist.

### PR DESCRIPTION
**Pull request by fredcooke**
"Optional requirements" is an oxymoron. As such, I have fixed your README.md file. Please merge, or, preferably, rebase this into, or onto, respectively, your master branch! Thank you kindly.

### CODE REVIEW

**Comment by masterkorp** [comment]
thumbs-up

**Comment by fredcooke** [comment]
The most useful thing in this thread, so far, is a GIF from a children's movie. The only thing that could top the GIF is acceptance of the PR and a peaceful and rightful closure thereof.

**Comment by psychon** [comment]
I don't have much to say/decide, but my 5 cent for bike-shedding would be: "Dependencies" instead of "Requirements" (That works for both "Minimal Dependencies" and "Optional Dependencies"; plus I think it better captures the intend of the 'sentence').

**Comment by fredcooke** [comment]
Sorry, something that is optional is not a dependency. If you are dependent on something (such as oxygen) it's certainly not optional. This is in the general context of the application. In the sub context of the optional feature being used, then yes, they're a dependency, and a requirement (only of the optional feature, though, not the context of the readme file), but they're still neither, as they're optional.

**Comment by psychon** [comment]
Hm, ok.

**Comment by dgw** [comment]
I'm just going to leave [this usage discussion](http://programmers.stackexchange.com/a/141421/3698) here… and quote the most relevant paragraph:

> I believe the confusion comes from the term "requirement". In the English language, a requirement is "a thing that is needed" or "a mandatory, compulsory, or necessary condition". However, in software engineering, the term requirement is simply a documented characteristic of a software system. The concept of optional and mandatory describe the priority of the documented characteristic of the software system.

**Comment by fredcooke** [comment]
The quality of that link is approximately equivalent to the quality of the prose in the offending document. As such reading it is entirely optional, and in no way required.

**Comment by fredcooke** [comment]
A comment from Iceland:

**Comment by fredcooke** [comment]
A comment from Iceland: Are they optional or are they requirements? They can't be both.
A comment from Canada: It's fairly clear from context that the error is the word "requirement".
A comment about Python developers: requirements.txt should probably hold product owner/user specifications about what the system should be able to do ;-)

**Comment by Zarthus** [comment]
I'm all for keeping this PR open for as long as possible to see how many more comments fredcooke will come up with.

**Comment by fredcooke** [comment]
You can still comment after it's closed ;-)

**Comment by Zarthus** [comment]
yeah, but you can't merge it

**Pull request closed without merging**
