### PR TITLE
Add ATTACH command

### PR DESCRIPTION
**Pull request by jpnurmi**
The main benefit is that (unlike JOIN) ATTACH allows wildcards. It's also nicely symmetric with DETACH.

### CODE REVIEW

**Comment by jpnurmi** [comment]
The idea of detaching queries didn't seem too popular, so I've separated the attach-related commits from #1014.

**Comment by DarthGandalf** [comment]
How do you measure popularity of a feature which isn't even merged yet? Especially if we don't have any stats on what features are used by users

**Comment by KindOne-** [comment]
A few people have joined #znc asking how to re-attach to all the channels at once or whatever.

**Comment by jpnurmi** [comment]
https://github.com/znc/znc/compare/1a3e9ecb8660...7f0348489937

**Pull request closed without merging**
