### PR TITLE
Implement table sorting in webadmin, addresses #40

### PR DESCRIPTION
**Pull request by ammaraskar**
Here's what it looks like

I still need to sort out the fixing odd and even rows after the tables are sorted.
Mainly I wanted your opinion on
* Whether this vanilla js solution is fine, or should I use the recent-ish added jquery for maximum compatibility. I believe the main limitation here is its >=IE9 with some of the functions I use. 
* Are the simple little arrows okay
* Is the formatting etc fine

Personally I agree with psychon on the issue page that using a really hefty library is kinda overkill. Which is why I opted to just make a simple sorting function.

### CODE REVIEW

**Comment by jpnurmi** [comment]
I also like the simple sort function approach, but I don't know what is the policy for supported browsers.

PS. Is that 'BLACK UP/DOWN-POINTING TRIANGLE'? To me, looks quite massive. :) How about 'BLACK UP/DOWN-POINTING SMALL TRIANGLE'?

**Comment by ammaraskar** [comment]
Yup, here's what BLACK UP/DOWN-POINTING SMALL TRIANGLE looks like.



small looks better in my opinion, so that leaves the last concern as maximum browser compatibility with dependence on jquery vs a vanilla js solution that doesn't support less than IE9. Looks like that accounts for [1.4% of the total browser market share](http://www.w3schools.com/browsers/browsers_explorer.asp).

**Comment by DarthGandalf** [comment]
I don't know web development at all, so disregard this my comment. But if it's possible to use jQuery to support more browsers, and still not bring some huge library, that would be good, I guess.

**Comment by DarthGandalf** [comment]
It's hard to reason about compatibility with browsers, unless all supported browsers are actually tested (something like #772?)

**Comment by ammaraskar** [comment]
>I don't know web development at all, so disregard this my comment. But if it's possible to use jQuery to support more browsers, and still not bring some huge library, that would be good, I guess.

I thought about it a bit and I have to say that znc is a technically orientated tool, I doubt there's much overlap between people with super outdated versions of IE and people who use znc. But anyway, I was initially off putted from jQuery by the discussion in the issue, namely the fact that it's so large and its use here would be so limited.
In conclusion: I feel that this is fine as it is.

>It's hard to reason about compatibility with browsers, unless all supported browsers are actually tested (something like #772?)

ehh, automated testing of browser compatibility is really overkill, I don't think there's nearly enough web code in this project to justify that

**Pull request merged**
